# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(392, 522)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 30, 258, 471))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_conectar = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_conectar.setObjectName("pushButton_conectar")
        self.gridLayout.addWidget(self.pushButton_conectar, 5, 1, 1, 1)
        self.treeView = QtWidgets.QTreeView(self.layoutWidget)
        self.treeView.setObjectName("treeView")
        self.gridLayout.addWidget(self.treeView, 4, 0, 1, 3)
        self.comboBox_bancoDados = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_bancoDados.setObjectName("comboBox_bancoDados")
        self.gridLayout.addWidget(self.comboBox_bancoDados, 1, 1, 1, 2)
        self.pushButton_cancelar = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_cancelar.setObjectName("pushButton_cancelar")
        self.gridLayout.addWidget(self.pushButton_cancelar, 5, 2, 1, 1)
        self.label_statusConexao = QtWidgets.QLabel(self.layoutWidget)
        self.label_statusConexao.setObjectName("label_statusConexao")
        self.gridLayout.addWidget(self.label_statusConexao, 0, 0, 1, 1)
        self.label_bancoDados = QtWidgets.QLabel(self.layoutWidget)
        self.label_bancoDados.setObjectName("label_bancoDados")
        self.gridLayout.addWidget(self.label_bancoDados, 1, 0, 1, 1)
        self.pushButton_extrair = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_extrair.setObjectName("pushButton_extrair")
        self.gridLayout.addWidget(self.pushButton_extrair, 5, 0, 1, 1)
        self.label_StatusConexao_retorno = QtWidgets.QLabel(self.layoutWidget)
        self.label_StatusConexao_retorno.setObjectName("label_StatusConexao_retorno")
        self.gridLayout.addWidget(self.label_StatusConexao_retorno, 0, 1, 1, 2)
        self.label_projeto = QtWidgets.QLabel(self.layoutWidget)
        self.label_projeto.setObjectName("label_projeto")
        self.gridLayout.addWidget(self.label_projeto, 2, 0, 1, 1)
        self.comboBox_projeto = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_projeto.setObjectName("comboBox_projeto")
        self.gridLayout.addWidget(self.comboBox_projeto, 2, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_conectar.setText(_translate("MainWindow", "Conectar"))
        self.pushButton_cancelar.setText(_translate("MainWindow", "Cancela"))
        self.label_statusConexao.setText(_translate("MainWindow", "Status Conexão"))
        self.label_bancoDados.setText(_translate("MainWindow", "Banco Dados"))
        self.pushButton_extrair.setText(_translate("MainWindow", "Extrair"))
        self.label_StatusConexao_retorno.setText(
            _translate("MainWindow", "Sem conexão")
        )
        self.label_projeto.setText(_translate("MainWindow", "Projeto"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
