# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiMainWindow(object):
    def setup_ui(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(393, 450) # Redimensionado para remover espaço vazio
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.layout_widget = QtWidgets.QWidget(self.centralwidget)
        self.layout_widget.setGeometry(QtCore.QRect(60, 30, 258, 360)) # Reajustado
        self.layout_widget.setObjectName("layout_widget")
        self.grid_layout = QtWidgets.QGridLayout(self.layout_widget)
        self.grid_layout.setContentsMargins(0, 0, 0, 0)
        
        # Removidos: push_button_cancelar e push_button_conectar
        
        self.label_projeto = QtWidgets.QLabel(self.layout_widget)
        self.label_projeto.setObjectName("label_projeto")
        self.grid_layout.addWidget(self.label_projeto, 5, 0, 1, 1)
        self.push_button_extrair = QtWidgets.QPushButton(self.layout_widget)
        self.push_button_extrair.setObjectName("push_button_extrair")
        self.grid_layout.addWidget(self.push_button_extrair, 8, 0, 1, 3) # Ocupa 3 colunas
        self.label_banco_dados = QtWidgets.QLabel(self.layout_widget)
        self.label_banco_dados.setObjectName("label_banco_dados")
        self.grid_layout.addWidget(self.label_banco_dados, 4, 0, 1, 1)
        self.label_status_conexao = QtWidgets.QLabel(self.layout_widget)
        self.label_status_conexao.setObjectName("label_status_conexao")
        self.grid_layout.addWidget(self.label_status_conexao, 2, 0, 1, 1)
        self.label_status_conexao_retorno = QtWidgets.QLabel(self.layout_widget)
        self.label_status_conexao_retorno.setObjectName("label_status_conexao_retorno")
        self.grid_layout.addWidget(self.label_status_conexao_retorno, 2, 1, 1, 2)
        self.tree_view = QtWidgets.QTreeView(self.layout_widget)
        self.tree_view.setObjectName("tree_view")
        self.grid_layout.addWidget(self.tree_view, 7, 0, 1, 3)
        self.combo_box_banco_dados = QtWidgets.QComboBox(self.layout_widget)
        self.combo_box_banco_dados.setObjectName("combo_box_banco_dados")
        self.grid_layout.addWidget(self.combo_box_banco_dados, 4, 1, 1, 2)
        self.combo_box_projeto = QtWidgets.QComboBox(self.layout_widget)
        self.combo_box_projeto.setObjectName("combo_box_projeto")
        self.grid_layout.addWidget(self.combo_box_projeto, 5, 1, 1, 2)
        self.horizontal_layout = QtWidgets.QHBoxLayout()
        self.horizontal_layout.setObjectName("horizontal_layout")
        self.line_edit_diretorio = QtWidgets.QLineEdit(self.layout_widget)
        self.line_edit_diretorio.setObjectName("line_edit_diretorio")
        self.horizontal_layout.addWidget(self.line_edit_diretorio)
        self.tool_button = QtWidgets.QToolButton(self.layout_widget)
        self.tool_button.setObjectName("tool_button")
        self.horizontal_layout.addWidget(self.tool_button)
        self.grid_layout.addLayout(self.horizontal_layout, 3, 0, 1, 3)
        main_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslate_ui(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslate_ui(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("MainWindow", "Gerador de Relatórios Cadastrais"))
        # Removidos: textos de push_button_cancelar e push_button_conectar
        self.label_projeto.setText(_translate("MainWindow", "Projeto"))
        self.push_button_extrair.setText(_translate("MainWindow", "Extrair"))
        self.label_banco_dados.setText(_translate("MainWindow", "Banco de Dados"))
        self.label_status_conexao.setText(_translate("MainWindow", "Status Conexão"))
        self.label_status_conexao_retorno.setText(
            _translate("MainWindow", "Sem conexão")
        )
        self.tool_button.setText(_translate("MainWindow", "..."))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = UiMainWindow()
    ui.setup_ui(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())